#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVienHVKTQS.Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyThuVienHVKTQS")]
	public partial class QuanLiThuVienHVKTQSDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertdocgia(docgia instance);
    partial void Updatedocgia(docgia instance);
    partial void Deletedocgia(docgia instance);
    partial void Insertnhanvien(nhanvien instance);
    partial void Updatenhanvien(nhanvien instance);
    partial void Deletenhanvien(nhanvien instance);
    partial void Insertnhaxuatban(nhaxuatban instance);
    partial void Updatenhaxuatban(nhaxuatban instance);
    partial void Deletenhaxuatban(nhaxuatban instance);
    partial void Insertsach(sach instance);
    partial void Updatesach(sach instance);
    partial void Deletesach(sach instance);
    partial void InsertMuonSach(MuonSach instance);
    partial void UpdateMuonSach(MuonSach instance);
    partial void DeleteMuonSach(MuonSach instance);
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    #endregion
		
		public QuanLiThuVienHVKTQSDataContext() : 
				base(global::QuanLyThuVienHVKTQS.Properties.Settings.Default.QuanLyThuVienHVKTQSConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLiThuVienHVKTQSDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLiThuVienHVKTQSDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLiThuVienHVKTQSDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLiThuVienHVKTQSDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<docgia> docgias
		{
			get
			{
				return this.GetTable<docgia>();
			}
		}
		
		public System.Data.Linq.Table<nhanvien> nhanviens
		{
			get
			{
				return this.GetTable<nhanvien>();
			}
		}
		
		public System.Data.Linq.Table<nhaxuatban> nhaxuatbans
		{
			get
			{
				return this.GetTable<nhaxuatban>();
			}
		}
		
		public System.Data.Linq.Table<sach> saches
		{
			get
			{
				return this.GetTable<sach>();
			}
		}
		
		public System.Data.Linq.Table<MuonSach> MuonSaches
		{
			get
			{
				return this.GetTable<MuonSach>();
			}
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.docgia")]
	public partial class docgia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _sothe;
		
		private string _hoten;
		
		private string _email;
		
		private System.Nullable<System.DateTime> _ngaysinh;
		
		private string _gioitinh;
		
		private string _diachi;
		
		private string _socmtnd;
		
		private string _anhthe;
		
		private System.Nullable<System.DateTime> _ngaylamthe;
		
		private System.Nullable<System.DateTime> _handungthe;
		
		private EntitySet<MuonSach> _MuonSaches;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsotheChanging(int value);
    partial void OnsotheChanged();
    partial void OnhotenChanging(string value);
    partial void OnhotenChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnngaysinhChanging(System.Nullable<System.DateTime> value);
    partial void OnngaysinhChanged();
    partial void OngioitinhChanging(string value);
    partial void OngioitinhChanged();
    partial void OndiachiChanging(string value);
    partial void OndiachiChanged();
    partial void OnsocmtndChanging(string value);
    partial void OnsocmtndChanged();
    partial void OnanhtheChanging(string value);
    partial void OnanhtheChanged();
    partial void OnngaylamtheChanging(System.Nullable<System.DateTime> value);
    partial void OnngaylamtheChanged();
    partial void OnhandungtheChanging(System.Nullable<System.DateTime> value);
    partial void OnhandungtheChanged();
    #endregion
		
		public docgia()
		{
			this._MuonSaches = new EntitySet<MuonSach>(new Action<MuonSach>(this.attach_MuonSaches), new Action<MuonSach>(this.detach_MuonSaches));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sothe", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int sothe
		{
			get
			{
				return this._sothe;
			}
			set
			{
				if ((this._sothe != value))
				{
					this.OnsotheChanging(value);
					this.SendPropertyChanging();
					this._sothe = value;
					this.SendPropertyChanged("sothe");
					this.OnsotheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoten", DbType="NVarChar(50)")]
		public string hoten
		{
			get
			{
				return this._hoten;
			}
			set
			{
				if ((this._hoten != value))
				{
					this.OnhotenChanging(value);
					this.SendPropertyChanging();
					this._hoten = value;
					this.SendPropertyChanged("hoten");
					this.OnhotenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaysinh", DbType="Date")]
		public System.Nullable<System.DateTime> ngaysinh
		{
			get
			{
				return this._ngaysinh;
			}
			set
			{
				if ((this._ngaysinh != value))
				{
					this.OnngaysinhChanging(value);
					this.SendPropertyChanging();
					this._ngaysinh = value;
					this.SendPropertyChanged("ngaysinh");
					this.OnngaysinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioitinh", DbType="NChar(10)")]
		public string gioitinh
		{
			get
			{
				return this._gioitinh;
			}
			set
			{
				if ((this._gioitinh != value))
				{
					this.OngioitinhChanging(value);
					this.SendPropertyChanging();
					this._gioitinh = value;
					this.SendPropertyChanged("gioitinh");
					this.OngioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="NVarChar(50)")]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this.OndiachiChanging(value);
					this.SendPropertyChanging();
					this._diachi = value;
					this.SendPropertyChanged("diachi");
					this.OndiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_socmtnd", DbType="VarChar(50)")]
		public string socmtnd
		{
			get
			{
				return this._socmtnd;
			}
			set
			{
				if ((this._socmtnd != value))
				{
					this.OnsocmtndChanging(value);
					this.SendPropertyChanging();
					this._socmtnd = value;
					this.SendPropertyChanged("socmtnd");
					this.OnsocmtndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anhthe", DbType="VarChar(50)")]
		public string anhthe
		{
			get
			{
				return this._anhthe;
			}
			set
			{
				if ((this._anhthe != value))
				{
					this.OnanhtheChanging(value);
					this.SendPropertyChanging();
					this._anhthe = value;
					this.SendPropertyChanged("anhthe");
					this.OnanhtheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaylamthe", DbType="Date")]
		public System.Nullable<System.DateTime> ngaylamthe
		{
			get
			{
				return this._ngaylamthe;
			}
			set
			{
				if ((this._ngaylamthe != value))
				{
					this.OnngaylamtheChanging(value);
					this.SendPropertyChanging();
					this._ngaylamthe = value;
					this.SendPropertyChanged("ngaylamthe");
					this.OnngaylamtheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_handungthe", DbType="Date")]
		public System.Nullable<System.DateTime> handungthe
		{
			get
			{
				return this._handungthe;
			}
			set
			{
				if ((this._handungthe != value))
				{
					this.OnhandungtheChanging(value);
					this.SendPropertyChanging();
					this._handungthe = value;
					this.SendPropertyChanged("handungthe");
					this.OnhandungtheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="docgia_MuonSach", Storage="_MuonSaches", ThisKey="sothe", OtherKey="sothe")]
		public EntitySet<MuonSach> MuonSaches
		{
			get
			{
				return this._MuonSaches;
			}
			set
			{
				this._MuonSaches.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MuonSaches(MuonSach entity)
		{
			this.SendPropertyChanging();
			entity.docgia = this;
		}
		
		private void detach_MuonSaches(MuonSach entity)
		{
			this.SendPropertyChanging();
			entity.docgia = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nhanvien")]
	public partial class nhanvien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _manv;
		
		private string _tennv;
		
		private string _sdt;
		
		private System.Nullable<System.DateTime> _ngaysinh;
		
		private string _gioitinh;
		
		private string _diachi;
		
		private string _socmtnd;
		
		private string _anh;
		
		private string _quyenhan;
		
		private string _matkhau;
		
		private string _note;
		
		private EntitySet<MuonSach> _MuonSaches;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmanvChanging(int value);
    partial void OnmanvChanged();
    partial void OntennvChanging(string value);
    partial void OntennvChanged();
    partial void OnsdtChanging(string value);
    partial void OnsdtChanged();
    partial void OnngaysinhChanging(System.Nullable<System.DateTime> value);
    partial void OnngaysinhChanged();
    partial void OngioitinhChanging(string value);
    partial void OngioitinhChanged();
    partial void OndiachiChanging(string value);
    partial void OndiachiChanged();
    partial void OnsocmtndChanging(string value);
    partial void OnsocmtndChanged();
    partial void OnanhChanging(string value);
    partial void OnanhChanged();
    partial void OnquyenhanChanging(string value);
    partial void OnquyenhanChanged();
    partial void OnmatkhauChanging(string value);
    partial void OnmatkhauChanged();
    partial void OnnoteChanging(string value);
    partial void OnnoteChanged();
    #endregion
		
		public nhanvien()
		{
			this._MuonSaches = new EntitySet<MuonSach>(new Action<MuonSach>(this.attach_MuonSaches), new Action<MuonSach>(this.detach_MuonSaches));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manv", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int manv
		{
			get
			{
				return this._manv;
			}
			set
			{
				if ((this._manv != value))
				{
					this.OnmanvChanging(value);
					this.SendPropertyChanging();
					this._manv = value;
					this.SendPropertyChanged("manv");
					this.OnmanvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tennv", DbType="NVarChar(50)")]
		public string tennv
		{
			get
			{
				return this._tennv;
			}
			set
			{
				if ((this._tennv != value))
				{
					this.OntennvChanging(value);
					this.SendPropertyChanging();
					this._tennv = value;
					this.SendPropertyChanged("tennv");
					this.OntennvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdt", DbType="VarChar(50)")]
		public string sdt
		{
			get
			{
				return this._sdt;
			}
			set
			{
				if ((this._sdt != value))
				{
					this.OnsdtChanging(value);
					this.SendPropertyChanging();
					this._sdt = value;
					this.SendPropertyChanged("sdt");
					this.OnsdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaysinh", DbType="Date")]
		public System.Nullable<System.DateTime> ngaysinh
		{
			get
			{
				return this._ngaysinh;
			}
			set
			{
				if ((this._ngaysinh != value))
				{
					this.OnngaysinhChanging(value);
					this.SendPropertyChanging();
					this._ngaysinh = value;
					this.SendPropertyChanged("ngaysinh");
					this.OnngaysinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioitinh", DbType="NChar(10)")]
		public string gioitinh
		{
			get
			{
				return this._gioitinh;
			}
			set
			{
				if ((this._gioitinh != value))
				{
					this.OngioitinhChanging(value);
					this.SendPropertyChanging();
					this._gioitinh = value;
					this.SendPropertyChanged("gioitinh");
					this.OngioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="NVarChar(50)")]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this.OndiachiChanging(value);
					this.SendPropertyChanging();
					this._diachi = value;
					this.SendPropertyChanged("diachi");
					this.OndiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_socmtnd", DbType="VarChar(50)")]
		public string socmtnd
		{
			get
			{
				return this._socmtnd;
			}
			set
			{
				if ((this._socmtnd != value))
				{
					this.OnsocmtndChanging(value);
					this.SendPropertyChanging();
					this._socmtnd = value;
					this.SendPropertyChanged("socmtnd");
					this.OnsocmtndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anh", DbType="VarChar(50)")]
		public string anh
		{
			get
			{
				return this._anh;
			}
			set
			{
				if ((this._anh != value))
				{
					this.OnanhChanging(value);
					this.SendPropertyChanging();
					this._anh = value;
					this.SendPropertyChanged("anh");
					this.OnanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quyenhan", DbType="VarChar(50)")]
		public string quyenhan
		{
			get
			{
				return this._quyenhan;
			}
			set
			{
				if ((this._quyenhan != value))
				{
					this.OnquyenhanChanging(value);
					this.SendPropertyChanging();
					this._quyenhan = value;
					this.SendPropertyChanged("quyenhan");
					this.OnquyenhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matkhau", DbType="VarChar(50)")]
		public string matkhau
		{
			get
			{
				return this._matkhau;
			}
			set
			{
				if ((this._matkhau != value))
				{
					this.OnmatkhauChanging(value);
					this.SendPropertyChanging();
					this._matkhau = value;
					this.SendPropertyChanged("matkhau");
					this.OnmatkhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_note", DbType="NVarChar(250)")]
		public string note
		{
			get
			{
				return this._note;
			}
			set
			{
				if ((this._note != value))
				{
					this.OnnoteChanging(value);
					this.SendPropertyChanging();
					this._note = value;
					this.SendPropertyChanged("note");
					this.OnnoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhanvien_MuonSach", Storage="_MuonSaches", ThisKey="manv", OtherKey="manv")]
		public EntitySet<MuonSach> MuonSaches
		{
			get
			{
				return this._MuonSaches;
			}
			set
			{
				this._MuonSaches.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MuonSaches(MuonSach entity)
		{
			this.SendPropertyChanging();
			entity.nhanvien = this;
		}
		
		private void detach_MuonSaches(MuonSach entity)
		{
			this.SendPropertyChanging();
			entity.nhanvien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nhaxuatban")]
	public partial class nhaxuatban : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _manxb;
		
		private string _tennxb;
		
		private string _diachi;
		
		private string _sdt;
		
		private EntitySet<sach> _saches;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmanxbChanging(int value);
    partial void OnmanxbChanged();
    partial void OntennxbChanging(string value);
    partial void OntennxbChanged();
    partial void OndiachiChanging(string value);
    partial void OndiachiChanged();
    partial void OnsdtChanging(string value);
    partial void OnsdtChanged();
    #endregion
		
		public nhaxuatban()
		{
			this._saches = new EntitySet<sach>(new Action<sach>(this.attach_saches), new Action<sach>(this.detach_saches));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manxb", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int manxb
		{
			get
			{
				return this._manxb;
			}
			set
			{
				if ((this._manxb != value))
				{
					this.OnmanxbChanging(value);
					this.SendPropertyChanging();
					this._manxb = value;
					this.SendPropertyChanged("manxb");
					this.OnmanxbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tennxb", DbType="NVarChar(50)")]
		public string tennxb
		{
			get
			{
				return this._tennxb;
			}
			set
			{
				if ((this._tennxb != value))
				{
					this.OntennxbChanging(value);
					this.SendPropertyChanging();
					this._tennxb = value;
					this.SendPropertyChanged("tennxb");
					this.OntennxbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="NVarChar(50)")]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this.OndiachiChanging(value);
					this.SendPropertyChanging();
					this._diachi = value;
					this.SendPropertyChanged("diachi");
					this.OndiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdt", DbType="VarChar(50)")]
		public string sdt
		{
			get
			{
				return this._sdt;
			}
			set
			{
				if ((this._sdt != value))
				{
					this.OnsdtChanging(value);
					this.SendPropertyChanging();
					this._sdt = value;
					this.SendPropertyChanged("sdt");
					this.OnsdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhaxuatban_sach", Storage="_saches", ThisKey="manxb", OtherKey="manxb")]
		public EntitySet<sach> saches
		{
			get
			{
				return this._saches;
			}
			set
			{
				this._saches.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_saches(sach entity)
		{
			this.SendPropertyChanging();
			entity.nhaxuatban = this;
		}
		
		private void detach_saches(sach entity)
		{
			this.SendPropertyChanging();
			entity.nhaxuatban = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sach")]
	public partial class sach : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _masach;
		
		private string _tensach;
		
		private string _tentacgia;
		
		private System.Nullable<int> _manxb;
		
		private System.Nullable<decimal> _giatien;
		
		private System.Nullable<int> _soluong;
		
		private string _ngonngu;
		
		private System.Nullable<int> _sotrang;
		
		private System.Nullable<int> _namxb;
		
		private string _theloai;
		
		private EntitySet<MuonSach> _MuonSaches;
		
		private EntityRef<nhaxuatban> _nhaxuatban;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmasachChanging(int value);
    partial void OnmasachChanged();
    partial void OntensachChanging(string value);
    partial void OntensachChanged();
    partial void OntentacgiaChanging(string value);
    partial void OntentacgiaChanged();
    partial void OnmanxbChanging(System.Nullable<int> value);
    partial void OnmanxbChanged();
    partial void OngiatienChanging(System.Nullable<decimal> value);
    partial void OngiatienChanged();
    partial void OnsoluongChanging(System.Nullable<int> value);
    partial void OnsoluongChanged();
    partial void OnngonnguChanging(string value);
    partial void OnngonnguChanged();
    partial void OnsotrangChanging(System.Nullable<int> value);
    partial void OnsotrangChanged();
    partial void OnnamxbChanging(System.Nullable<int> value);
    partial void OnnamxbChanged();
    partial void OntheloaiChanging(string value);
    partial void OntheloaiChanged();
    #endregion
		
		public sach()
		{
			this._MuonSaches = new EntitySet<MuonSach>(new Action<MuonSach>(this.attach_MuonSaches), new Action<MuonSach>(this.detach_MuonSaches));
			this._nhaxuatban = default(EntityRef<nhaxuatban>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_masach", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int masach
		{
			get
			{
				return this._masach;
			}
			set
			{
				if ((this._masach != value))
				{
					this.OnmasachChanging(value);
					this.SendPropertyChanging();
					this._masach = value;
					this.SendPropertyChanged("masach");
					this.OnmasachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tensach", DbType="NVarChar(150)")]
		public string tensach
		{
			get
			{
				return this._tensach;
			}
			set
			{
				if ((this._tensach != value))
				{
					this.OntensachChanging(value);
					this.SendPropertyChanging();
					this._tensach = value;
					this.SendPropertyChanged("tensach");
					this.OntensachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tentacgia", DbType="NVarChar(150)")]
		public string tentacgia
		{
			get
			{
				return this._tentacgia;
			}
			set
			{
				if ((this._tentacgia != value))
				{
					this.OntentacgiaChanging(value);
					this.SendPropertyChanging();
					this._tentacgia = value;
					this.SendPropertyChanged("tentacgia");
					this.OntentacgiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manxb", DbType="Int")]
		public System.Nullable<int> manxb
		{
			get
			{
				return this._manxb;
			}
			set
			{
				if ((this._manxb != value))
				{
					if (this._nhaxuatban.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmanxbChanging(value);
					this.SendPropertyChanging();
					this._manxb = value;
					this.SendPropertyChanged("manxb");
					this.OnmanxbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giatien", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> giatien
		{
			get
			{
				return this._giatien;
			}
			set
			{
				if ((this._giatien != value))
				{
					this.OngiatienChanging(value);
					this.SendPropertyChanging();
					this._giatien = value;
					this.SendPropertyChanged("giatien");
					this.OngiatienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soluong", DbType="Int")]
		public System.Nullable<int> soluong
		{
			get
			{
				return this._soluong;
			}
			set
			{
				if ((this._soluong != value))
				{
					this.OnsoluongChanging(value);
					this.SendPropertyChanging();
					this._soluong = value;
					this.SendPropertyChanged("soluong");
					this.OnsoluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngonngu", DbType="NVarChar(50)")]
		public string ngonngu
		{
			get
			{
				return this._ngonngu;
			}
			set
			{
				if ((this._ngonngu != value))
				{
					this.OnngonnguChanging(value);
					this.SendPropertyChanging();
					this._ngonngu = value;
					this.SendPropertyChanged("ngonngu");
					this.OnngonnguChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sotrang", DbType="Int")]
		public System.Nullable<int> sotrang
		{
			get
			{
				return this._sotrang;
			}
			set
			{
				if ((this._sotrang != value))
				{
					this.OnsotrangChanging(value);
					this.SendPropertyChanging();
					this._sotrang = value;
					this.SendPropertyChanged("sotrang");
					this.OnsotrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_namxb", DbType="Int")]
		public System.Nullable<int> namxb
		{
			get
			{
				return this._namxb;
			}
			set
			{
				if ((this._namxb != value))
				{
					this.OnnamxbChanging(value);
					this.SendPropertyChanging();
					this._namxb = value;
					this.SendPropertyChanged("namxb");
					this.OnnamxbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_theloai", DbType="NVarChar(50)")]
		public string theloai
		{
			get
			{
				return this._theloai;
			}
			set
			{
				if ((this._theloai != value))
				{
					this.OntheloaiChanging(value);
					this.SendPropertyChanging();
					this._theloai = value;
					this.SendPropertyChanged("theloai");
					this.OntheloaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sach_MuonSach", Storage="_MuonSaches", ThisKey="masach", OtherKey="masach")]
		public EntitySet<MuonSach> MuonSaches
		{
			get
			{
				return this._MuonSaches;
			}
			set
			{
				this._MuonSaches.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhaxuatban_sach", Storage="_nhaxuatban", ThisKey="manxb", OtherKey="manxb", IsForeignKey=true)]
		public nhaxuatban nhaxuatban
		{
			get
			{
				return this._nhaxuatban.Entity;
			}
			set
			{
				nhaxuatban previousValue = this._nhaxuatban.Entity;
				if (((previousValue != value) 
							|| (this._nhaxuatban.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._nhaxuatban.Entity = null;
						previousValue.saches.Remove(this);
					}
					this._nhaxuatban.Entity = value;
					if ((value != null))
					{
						value.saches.Add(this);
						this._manxb = value.manxb;
					}
					else
					{
						this._manxb = default(Nullable<int>);
					}
					this.SendPropertyChanged("nhaxuatban");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MuonSaches(MuonSach entity)
		{
			this.SendPropertyChanging();
			entity.sach = this;
		}
		
		private void detach_MuonSaches(MuonSach entity)
		{
			this.SendPropertyChanging();
			entity.sach = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MuonSach")]
	public partial class MuonSach : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Mamuon;
		
		private int _sothe;
		
		private int _masach;
		
		private System.Nullable<int> _soluong;
		
		private System.Nullable<System.DateTime> _ngaymuon;
		
		private System.Nullable<System.DateTime> _hantra;
		
		private int _manv;
		
		private EntityRef<docgia> _docgia;
		
		private EntityRef<nhanvien> _nhanvien;
		
		private EntityRef<sach> _sach;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMamuonChanging(int value);
    partial void OnMamuonChanged();
    partial void OnsotheChanging(int value);
    partial void OnsotheChanged();
    partial void OnmasachChanging(int value);
    partial void OnmasachChanged();
    partial void OnsoluongChanging(System.Nullable<int> value);
    partial void OnsoluongChanged();
    partial void OnngaymuonChanging(System.Nullable<System.DateTime> value);
    partial void OnngaymuonChanged();
    partial void OnhantraChanging(System.Nullable<System.DateTime> value);
    partial void OnhantraChanged();
    partial void OnmanvChanging(int value);
    partial void OnmanvChanged();
    #endregion
		
		public MuonSach()
		{
			this._docgia = default(EntityRef<docgia>);
			this._nhanvien = default(EntityRef<nhanvien>);
			this._sach = default(EntityRef<sach>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mamuon", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Mamuon
		{
			get
			{
				return this._Mamuon;
			}
			set
			{
				if ((this._Mamuon != value))
				{
					this.OnMamuonChanging(value);
					this.SendPropertyChanging();
					this._Mamuon = value;
					this.SendPropertyChanged("Mamuon");
					this.OnMamuonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sothe", DbType="Int NOT NULL")]
		public int sothe
		{
			get
			{
				return this._sothe;
			}
			set
			{
				if ((this._sothe != value))
				{
					if (this._docgia.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnsotheChanging(value);
					this.SendPropertyChanging();
					this._sothe = value;
					this.SendPropertyChanged("sothe");
					this.OnsotheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_masach", DbType="Int NOT NULL")]
		public int masach
		{
			get
			{
				return this._masach;
			}
			set
			{
				if ((this._masach != value))
				{
					if (this._sach.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmasachChanging(value);
					this.SendPropertyChanging();
					this._masach = value;
					this.SendPropertyChanged("masach");
					this.OnmasachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soluong", DbType="Int")]
		public System.Nullable<int> soluong
		{
			get
			{
				return this._soluong;
			}
			set
			{
				if ((this._soluong != value))
				{
					this.OnsoluongChanging(value);
					this.SendPropertyChanging();
					this._soluong = value;
					this.SendPropertyChanged("soluong");
					this.OnsoluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaymuon", DbType="Date")]
		public System.Nullable<System.DateTime> ngaymuon
		{
			get
			{
				return this._ngaymuon;
			}
			set
			{
				if ((this._ngaymuon != value))
				{
					this.OnngaymuonChanging(value);
					this.SendPropertyChanging();
					this._ngaymuon = value;
					this.SendPropertyChanged("ngaymuon");
					this.OnngaymuonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hantra", DbType="Date")]
		public System.Nullable<System.DateTime> hantra
		{
			get
			{
				return this._hantra;
			}
			set
			{
				if ((this._hantra != value))
				{
					this.OnhantraChanging(value);
					this.SendPropertyChanging();
					this._hantra = value;
					this.SendPropertyChanged("hantra");
					this.OnhantraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manv", DbType="Int NOT NULL")]
		public int manv
		{
			get
			{
				return this._manv;
			}
			set
			{
				if ((this._manv != value))
				{
					if (this._nhanvien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmanvChanging(value);
					this.SendPropertyChanging();
					this._manv = value;
					this.SendPropertyChanged("manv");
					this.OnmanvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="docgia_MuonSach", Storage="_docgia", ThisKey="sothe", OtherKey="sothe", IsForeignKey=true)]
		public docgia docgia
		{
			get
			{
				return this._docgia.Entity;
			}
			set
			{
				docgia previousValue = this._docgia.Entity;
				if (((previousValue != value) 
							|| (this._docgia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._docgia.Entity = null;
						previousValue.MuonSaches.Remove(this);
					}
					this._docgia.Entity = value;
					if ((value != null))
					{
						value.MuonSaches.Add(this);
						this._sothe = value.sothe;
					}
					else
					{
						this._sothe = default(int);
					}
					this.SendPropertyChanged("docgia");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhanvien_MuonSach", Storage="_nhanvien", ThisKey="manv", OtherKey="manv", IsForeignKey=true)]
		public nhanvien nhanvien
		{
			get
			{
				return this._nhanvien.Entity;
			}
			set
			{
				nhanvien previousValue = this._nhanvien.Entity;
				if (((previousValue != value) 
							|| (this._nhanvien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._nhanvien.Entity = null;
						previousValue.MuonSaches.Remove(this);
					}
					this._nhanvien.Entity = value;
					if ((value != null))
					{
						value.MuonSaches.Add(this);
						this._manv = value.manv;
					}
					else
					{
						this._manv = default(int);
					}
					this.SendPropertyChanged("nhanvien");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sach_MuonSach", Storage="_sach", ThisKey="masach", OtherKey="masach", IsForeignKey=true)]
		public sach sach
		{
			get
			{
				return this._sach.Entity;
			}
			set
			{
				sach previousValue = this._sach.Entity;
				if (((previousValue != value) 
							|| (this._sach.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._sach.Entity = null;
						previousValue.MuonSaches.Remove(this);
					}
					this._sach.Entity = value;
					if ((value != null))
					{
						value.MuonSaches.Add(this);
						this._masach = value.masach;
					}
					else
					{
						this._masach = default(int);
					}
					this.SendPropertyChanged("sach");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[User]")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _UserName;
		
		private string _Password;
		
		private System.Nullable<bool> _IsAdmin;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnIsAdminChanging(System.Nullable<bool> value);
    partial void OnIsAdminChanged();
    #endregion
		
		public User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(32) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAdmin", DbType="Bit")]
		public System.Nullable<bool> IsAdmin
		{
			get
			{
				return this._IsAdmin;
			}
			set
			{
				if ((this._IsAdmin != value))
				{
					this.OnIsAdminChanging(value);
					this.SendPropertyChanging();
					this._IsAdmin = value;
					this.SendPropertyChanged("IsAdmin");
					this.OnIsAdminChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
